export const texts = {
  main_text: "main_text",
  starting: "starting",
  name_surname: "name_surname",
  user_info: "user_info",
  not_confirmed: "not_confirmed",
  location: "location",
  change_location: "change_location",
  confirmed: "confirmed",
  add_new_info: "add_new_info",
  not_new_info: "not_new_info",
  main_menu: "main_menu",
  go_back: "go_back",
  skip_btn: "skip_btn",
  join: "join",
  joined: "joined",
  user_address: "user_address",
  orientr: "orientr",
  telephone: "telephone",
  extra_info: "extra_info",
  choosed: "choosed",
  location_access: "location_access",
  share: "share",
  confirm: "confirm",
  cancel: "cancel",

  user_infos: {
    add_birthday: "add_birthday",
    user_name_surname: "user_name_surname",
    birthday: "birthday",
    add_address: "add_address",
    add_location: "add_location",
    add_location_req_btn: "add_location_req_btn",
    add_location_err: "add_location_err",
    add_phone: "add_phone",
    add_phone_req_btn: "add_phone_req_btn",
    add_phone_err: "add_phone_err",
    add_extra_phone: "add_extra_phone",
    add_extra_phone_err: "add_extra_phone_err",
    add_description: "add_description",
    add_description_err: "add_description_err",
  },
  namesername: "namesername",
  birthday: "birthday",
  useraddress: "useraddress",
};
